name: Static analysis

on:
  pull_request:
    branches: [ "master" ]

jobs:
  psalm:
    name: PHP ${{ matrix.php }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        php: [ '8.0', '8.1' ]
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Build
        run: make build v=${{ matrix.php }}

      - name: Static analysis
        run: make analyse v=${{ matrix.php }}