name: Run tests
on:
  pull_request:
    branches: [ "master" ]
  push:
    branches: [ "master" ]

jobs:
  codeception:
    name: PHP ${{ matrix.php }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        php: [ '8.0', '8.1' ]
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Build
        run: make build v=${{ matrix.php }}

      - name: PHP Codeception tests for PHP ${{ matrix.php }}
        run: make test v=${{ matrix.php }}